(define (problem hotelprob5) (:domain hotel2)
(:objects 
    qs1 qs2 qs3 qs4 - quartosimples
    qd1 qd2 qd3 qd4 - quartoduplo
    qq1 qq2 qq3 qq4 - quartoquadruplo
    joao maria carla bruno - hospede
    man1 wm1 man2 wm2 wm3 wm4 - hospede
    amigo1 amigo2 amigo3 amigo4 - hospede
)

(:init
    (= (orcamento) 2200)
    (= (preco-quartoS qs1) 150)
    (= (preco-quartoS qs2) 150)
    (= (preco-quartoS qs3) 150)
    (= (preco-quartoS qs4) 150)
    (= (preco-quartoD qd1) 225)
    (= (preco-quartoD qd2) 225)
    (= (preco-quartoD qd3) 225)
    (= (preco-quartoD qd4) 225)
    (= (preco-quartoQ qq1) 350)
    (= (preco-quartoQ qq2) 350)
    (= (preco-quartoQ qq3) 350)
    (= (preco-quartoQ qq4) 350)
    (= (ocupacaoS qs1) 0)
    (= (ocupacaoS qs2) 0)
    (= (ocupacaoS qs3) 0)
    (= (ocupacaoS qs4) 0)
    (= (ocupacaoD qd1) 0)
    (= (ocupacaoD qd2) 0)
    (= (ocupacaoD qd3) 0)
    (= (ocupacaoD qd4) 0)
    (= (ocupacaoQ qq1) 0)
    (= (ocupacaoQ qq2) 0)
    (= (ocupacaoQ qq3) 0)
    (= (ocupacaoQ qq4) 0)
    (sao-casal joao maria)
    (sao-casal carla bruno)
    (e-casal joao)
    (e-casal maria)
    (e-casal carla)
    (e-casal bruno)
    (se-odeiam joao carla)
    (se-odeiam joao wm1)
    (se-odeiam joao wm2)
    (se-odeiam joao wm3)
    (se-odeiam joao wm4)
    (se-odeiam joao bruno)
    (se-odeiam joao man1)
    (se-odeiam joao man2)
    (se-odeiam joao amigo1)
    (se-odeiam joao amigo2)
    (se-odeiam joao amigo3)
    (se-odeiam joao amigo4)
    (se-odeiam bruno man1)
    (se-odeiam bruno man2)
    (se-odeiam bruno amigo1)
    (se-odeiam bruno amigo2)
    (se-odeiam bruno amigo3)
    (se-odeiam bruno amigo4)
    (se-odeiam bruno maria)
    (se-odeiam bruno wm1)
    (se-odeiam bruno wm2)
    (se-odeiam bruno wm3)
    (se-odeiam bruno wm4)
    (se-odeiam carla joao)
    (se-odeiam carla man1)
    (se-odeiam carla man2)
    (se-odeiam carla amigo1)
    (se-odeiam carla amigo2)
    (se-odeiam carla amigo3)
    (se-odeiam carla amigo4)
    (se-odeiam maria bruno)
    (se-odeiam maria man1)
    (se-odeiam maria man2)
    (se-odeiam maria amigo1)
    (se-odeiam maria amigo2)
    (se-odeiam maria amigo3)
    (se-odeiam maria amigo4)
    (se-odeiam wm1 joao)
    (se-odeiam wm1 bruno)
    (se-odeiam wm1 man1)
    (se-odeiam wm1 man2)
    (se-odeiam wm1 amigo1)
    (se-odeiam wm1 amigo2)
    (se-odeiam wm1 amigo3)
    (se-odeiam wm1 amigo4)
    (se-odeiam wm2 joao)
    (se-odeiam wm2 bruno)
    (se-odeiam wm2 man1)
    (se-odeiam wm2 man2)
    (se-odeiam wm2 amigo1)
    (se-odeiam wm2 amigo2)
    (se-odeiam wm2 amigo3)
    (se-odeiam wm2 amigo4) 
    (se-odeiam wm3 joao)
    (se-odeiam wm3 bruno)
    (se-odeiam wm3 man1)
    (se-odeiam wm3 man2)
    (se-odeiam wm3 amigo1)
    (se-odeiam wm3 amigo2)
    (se-odeiam wm3 amigo3)
    (se-odeiam wm3 amigo4)
    (se-odeiam wm4 joao)
    (se-odeiam wm4 bruno)
    (se-odeiam wm4 man1)
    (se-odeiam wm4 man2)
    (se-odeiam wm4 amigo1)
    (se-odeiam wm4 amigo2)
    (se-odeiam wm4 amigo3)
    (se-odeiam wm4 amigo4)
)

(:goal (and
    (alocado joao)
    (alocado maria)
    (alocado carla)
    (alocado bruno)
    (alocado man1)
    (alocado man2)
    (alocado wm1)
    (alocado wm2)
    (alocado wm3)
    (alocado wm4)
    (alocado amigo1)
    (alocado amigo2)
    (alocado amigo3)
    (alocado amigo4)
))

;un-comment the following line if metric is needed
(:metric maximize (orcamento))
)

;(pagaoquartoduplo qd2)
;(pagaoquartoduplo qd1)
;(poenoquartoduplo wm2 wm1 qd1)
;(pagaoquartoduplo qd4)
;(poenoquartoduplo man2 amigo4 qd4)
;(pagaoquartoduplo qd3)
;(poenoquartoduplo amigo1 man1 qd3)
;(pagaoquartoquadruplo qq1)
;(poenoquartoquadruplo wm4 wm4 wm4 wm3 qq1)
;(pagaoquartosimples qs1)

;time: 313.388737667 seconds
;Deu time-out
