(define (problem hotelprob1) (:domain hotel2)
(:objects 
    qs1 qs2 qs3 qs4 - quartosimples
    qd1 qd2 qd3 qd4 - quartoduplo
    qt1 - quartotriplo
    qq1 qq2 qq3 qq4 - quartoquadruplo
    joao maria carla bruno - hospede
    man1 wm1 man2 wm2 - hospede
    amigo1 amigo2 amigo3 amigo4 - hospede
)

(:init
    (= (orcamento) 2000)
    (= (preco-quartoS qs1) 150)
    (= (preco-quartoS qs2) 150)
    (= (preco-quartoS qs3) 150)
    (= (preco-quartoS qs4) 150)
    (= (preco-quartoD qd1) 225)
    (= (preco-quartoD qd2) 225)
    (= (preco-quartoD qd3) 225)
    (= (preco-quartoD qd4) 225)
    (= (preco-quartoT qt1) 310)
    (= (preco-quartoQ qq1) 400)
    (= (preco-quartoQ qq2) 400)
    (= (preco-quartoQ qq3) 400)
    (= (preco-quartoQ qq4) 400)
    (= (ocupacaoS qs1) 0)
    (= (ocupacaoS qs2) 0)
    (= (ocupacaoS qs3) 0)
    (= (ocupacaoS qs4) 0)
    (= (ocupacaoD qd1) 0)
    (= (ocupacaoD qd2) 0)
    (= (ocupacaoD qd3) 0)
    (= (ocupacaoD qd4) 0)
    (= (ocupacaoT qt1) 0)
    (= (ocupacaoQ qq1) 0)
    (= (ocupacaoQ qq2) 0)
    (= (ocupacaoQ qq3) 0)
    (= (ocupacaoQ qq4) 0)
    (sao-casal joao maria)
    (sao-casal carla bruno)
    (e-casal joao)
    (e-casal maria)
    (e-casal carla)
    (e-casal bruno)
    (se-odeiam joao carla)
    (se-odeiam joao wm1)
    (se-odeiam joao wm2)
    (se-odeiam bruno maria)
    (se-odeiam bruno wm1)
    (se-odeiam bruno wm2)
    (se-odeiam carla joao)
    (se-odeiam carla man1)
    (se-odeiam carla man2)
    (se-odeiam carla amigo1)
    (se-odeiam carla amigo2)
    (se-odeiam carla amigo3)
    (se-odeiam carla amigo4)
    (se-odeiam maria bruno)
    (se-odeiam maria man1)
    (se-odeiam maria man2)
    (se-odeiam maria amigo1)
    (se-odeiam maria amigo2)
    (se-odeiam maria amigo3)
    (se-odeiam maria amigo4)
    (se-odeiam wm1 joao)
    (se-odeiam wm1 bruno)
    (se-odeiam wm1 man1)
    (se-odeiam wm1 man2)
    (se-odeiam wm1 amigo1)
    (se-odeiam wm1 amigo2)
    (se-odeiam wm1 amigo3)
    (se-odeiam wm1 amigo4)
    (se-odeiam wm2 joao)
    (se-odeiam wm2 bruno)
    (se-odeiam wm2 man1)
    (se-odeiam wm2 man2)
    (se-odeiam wm2 amigo1)
    (se-odeiam wm2 amigo2)
    (se-odeiam wm2 amigo3)
    (se-odeiam wm2 amigo4) 
)

(:goal (and
    (alocado joao)
    (alocado maria)
    (alocado carla)
    (alocado bruno)
    (alocado man1)
    (alocado wm1)
    (alocado man2)
    (alocado wm2)
    (alocado amigo1)
    (alocado amigo2)
    (alocado amigo3)
    (alocado amigo4)
))

;un-comment the following line if metric is needed
(:metric maximize (orcamento))
)

;(pagaoquartoduplo qd2)
;(pagaoquartotriplo qt1)
;(poenoquartotriplo man2 amigo4 amigo1 qt1)
;(pagaoquartoduplo qd1)
;(poenoquartoduplo wm2 wm1 qd1)
;(pagaoquartoduplo qd4)
;(poenoquartoduplo man1 amigo2 qd4)
;(pagaoquartoduplo qd3)
;(poecasal carla bruno qd3)
;(poecasal joao maria qd2)
;(pagaoquartosimples qs3)
;(poenoquartosimples amigo3 qs3)

;time: 18.550258942 seconds
